app:
  port: 8080
  mode: debug # debug, release
db:
  user: <your_db_username>
  password: <your_db_password>
  host: <your_db_host>
  port: <your_db_port>
  name: <your_db_name>
csv:
  path: <your_csv_path>
cron:
  spec: "0 0 * * *"
